.TH GRM "1" "May 2023" "" "User Commands"
.SH NAME
grm \- run GUI to manage git repositories
.SH SYNOPSIS
.B grm
.br
.B grm
\fI\,OPTION\/\fR
.SH DESCRIPTION
.PP
.B grm
is a program that will display graphical user interface that allows you to manage git repositories.
.SH OPTIONS
This program can be run with the following short options:
.TP
\fB\-h\fR
display usage and exit
.TP
\fB\-v\fR
output version and author information and exit
.TP
\fB\-l\fR
output list of imported repositories and exit
.SH AUTHOR
Written by Kamil Wenta.
.SH COPYRIGHT
Copyright \(co 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
